public enum TokenType {
    CURSO, ESTUDIANTE,
    MOSTRAR_CURSO, MOSTRAR_ESTUDIANTE,
    BUSCAR_ESTUDIANTE, ELIMINAR_ESTUDIANTE,
    NUMERO, IDENTIFICADOR,
    COMA, PUNTOYCOMA,
    PARENTESIS_IZQ, PARENTESIS_DER,
    FIN
}
